jobs:
- name: test-and-publish-framework
  plan:
  - aggregate:
    - get: framework-git
      trigger: true
    - get: framework-snapshot
    - get: ci-git
  - task: build-artifacts
    file: ci-git/tasks/build-artifacts/task.yml
  - task: update-snapshot
    file: ci-git/tasks/update-snapshot.yml
  - put: framework-artifact
    params:
      file: build-artifacts-output/framework-*.jar
      pom_file: build-artifacts-output/framework-*.pom
      version_file: build-artifacts-output/version
  - put: framework-snapshot
    params: {repository: update-snapshot-output}

resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: patrickcrocker/maven-resource
    tag: latest

resources:
- name: ci-git
  type: git
  source:
    uri: {{ci-git-uri}}
    branch: master
    private_key: {{git-private-key}}

- name: framework-git
  type: git
  source:
    uri: {{framework-git-uri}}
    branch: master
    private_key: {{git-private-key}}

# - name: framework-version
#   type: semver
#   source:
#     driver: git
#     initial_version: 1.0.0
#     uri: {{framework-version-uri}}
#     branch: {{framework-version-branch}}
#     file: version
#     private_key: {{git-private-key}}

- name: framework-snapshot
  type: git
  source:
    uri: {{framework-snapshot-uri}}
    branch: {{framework-snapshot-branch}}
    private_key: {{git-private-key}}

# - name: client-git
#   type: git
#   source:
#     uri: {{client-git-uri}}
#     branch: master
#     private_key: {{git-private-key}}

- name: framework-artifact
  type: maven-resource
  source:
    url: {{nexus-uri}}
    artifact: com.example:framework:pom
    username: {{nexus-username}}
    password: {{nexus-password}}
    skip_cert_check: true
