---
jobs:
- name: test-and-publish-framework
  plan:
  - aggregate:
    - get: pipeline
    - get: project
      resource: framework-git
      trigger: true
  - task: build-artifacts
    file: pipeline/tasks/build-artifacts.yml
  - put: framework-artifact
    params:
      file: build-artifacts-output/framework-*.jar
      pom_file: build-artifacts-output/framework-*.pom

- name: test-and-publish-client
  plan:
  - aggregate:
    - get: pipeline
    - get: project
      resource: client-git
      trigger: true
    - get: framework-artifact
      trigger: true
  - task: build-artifacts
    file: pipeline/tasks/build-artifacts.yml
  - put: client-artifact
    params:
      file: build-artifacts-output/client-*.jar
      pom_file: build-artifacts-output/client-*.pom

resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: patrickcrocker/maven-resource
    tag: 1.2.0-rc.13

resources:
- name: pipeline
  type: git
  source:
    uri: {{ci-git-uri}}
    branch: master
    private_key: {{git-private-key}}

- name: framework-git
  type: git
  source:
    uri: {{framework-git-uri}}
    branch: master
    private_key: {{git-private-key}}

- name: client-git
  type: git
  source:
    uri: {{client-git-uri}}
    branch: master
    private_key: {{git-private-key}}

- name: framework-artifact
  type: maven-resource
  source:
    url: {{nexus-release-uri}}
    snapshot_url: {{nexus-snapshot-uri}}
    artifact: com.example:framework:jar
    username: {{nexus-username}}
    password: {{nexus-password}}
    skip_cert_check: true

- name: client-artifact
  type: maven-resource
  source:
    url: {{nexus-release-uri}}
    snapshot_url: {{nexus-snapshot-uri}}
    artifact: com.example:client:jar
    username: {{nexus-username}}
    password: {{nexus-password}}
    skip_cert_check: true
