---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk-alpine'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:
  MAVEN_REPO_MIRROR:
  MAVEN_REPO_USERNAME:
  MAVEN_REPO_PASSWORD:
  ARTIFACT_GLOB:

inputs:
  - name: ci-git
  - name: framework-git
  - name: framework-snapshot

outputs:
  - name: publish-jars-output

run:
  path: ci-git/tasks/publish-framework-jars/task.sh
